<?php
include('clases\config.php');
include('clases\campos_categoria.php');
include('clases\campos_cliente.php');
include('clases\campos_proveedores.php');
include('clases\campos_empleados.php');
include('clases\campos_inventario_producto.php');
include('clases\campos_inventario_materia.php');
include('clases\conexion.php');